version: '3'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - fullcycle-network
    restart: unless-stopped

  node-app:
    build: ./node-app
    volumes:
      - ./node-app:/app
      - /app/node_modules
    networks:
      - fullcycle-network
    restart: unless-stopped
    depends_on:
      - db

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    networks:
      - fullcycle-network
    restart: unless-stopped

networks:
  fullcycle-network:
    driver: bridge
