version: '3.8'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - fullcycle-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

  node-app:
    build: ./node-app
    volumes:
      - ./node-app:/app
      - /app/node_modules
    networks:
      - fullcycle-network
    depends_on:
      db:
        condition: service_healthy
    restart: always

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    networks:
      - fullcycle-network
    depends_on:
      node-app:
        condition: service_started
    restart: always

networks:
  fullcycle-network:
    driver: bridge
